### ISSUE TITLE
Question: Please clarify purpose and correct usage of certain source files.

### ISSUE THREAD

**Issue by jcheroske** [resisttheurge/babel-webpack-package-boilerplate#2]
I'm building a simple package, that only has one exported function. I am a bit confused by the following files and how to use them:

src/lib/index.js
src/lib/[moduleName]/index.js
src/main.js

If you were building a module with one source file and one named export, how would you structure the code and why?

Thanks!

**Comment by resisttheurge** [comment]
This boilerplate is a little over-engineered for your use case, but it should be relatively easy to configure. 

# The Files in Question

First, an explanation of the files. This boilerplate was designed to be used as a combined executable/library package. That means that installing the package would install an executable command and a library file.

`src/main.js`
This is the source file for the main executable script. It is what would be called if you installed the package and executed the installed command from the command line. It will be compiled by webpack, and the compiled file will be referenced from the shell-executable script in `bin/main.js`.

`bin/main.js`
This is a shell-executable script, referenced by the `bin['babel-webpack-package-boilerplate']` configuration option in the project's `package.json` file. This simply executes the compiled files for `src/main.js`.

`src/lib/index.js`
This is the source file for all exported library functionality. It is compiled by webpack separately from `src/main.js` and can be used to export functionality to other modules. Since it is referenced by the `main` configuration option of the project's `package.json` file, users importing the the project will automatically get the exported contents of the `src/lib/index.js` module.

`src/lib/[moduleName]/index.js`
This would be a sharable source file for a bit of reusable code within your project. The benefit of placing it within the lib folder is that it can be easily accessed by both `src/main.js` and `src/lib/index.js`, which means if you're creating a combined package like the boilerplate is intended to be, you can reuse code more effectively between the two halves of the project. 

# What to Do

Obviously, in your case, much of the reasoning behind the structure of the boilerplate no longer holds water. In order to keep the complexity of this answer down, I'm going to recommend changing only a few pieces of the puzzle. This means that some vestigial directories and scripts will remain, but the general goal will be achieved. If you want to restructure the project more thoroughly, feel free.

First, remove the `bin` configuration option from the project's `package.json`.
Then, delete the `bin` folder and its contents, as well as `src/main.js`.
Then open `config/io.js` file and remove the `main` field from the `entry` object.
```javascript
'use strict'

const { paths: { src, dist } } = require('./paths')

const entry = {
  lib: ['babel-polyfill', src('lib')]
}

const output = {
  path: dist(),
  filename: '[name].js'
}

module.exports = { entry, output }
```
Finally, put any reusable code in modules inside of `src/lib/` and export your package-level exports in the `src/lib/index.js` file. They should be accessible directly from any `require('babel-webpack-package-boilerplate') import!

Hope that helps. Again, let me know if this solves your problem so I can close the issue, and otherwise, keep asking questions! I'm happy to answer.

**Comment by jcheroske** [comment]
Wow, what an awesome reply (as is your other one). You're a natural mentor.

I'm going to axe those files and bits of config and give it a go.
